package main;

import org.jfree.ui.RefineryUtilities;

import agents.Predator;
import agents.Prey;

public class MainSoftmaxQL {

	public static void main(String[] args) {
		
		SoftmaxQLearning env = new SoftmaxQLearning(new Predator(0, 0),
				new Prey(5, 5));
		//env.run();
		double alpha = 0.1;
		double gamma = 0.2;
		double[][] parameterSettings = {{alpha,gamma,0.1,15}, {alpha, gamma, 1, 15}, {alpha, gamma, 10, 15},{alpha, gamma, 100, 15}};
		env.run(parameterSettings);
		// Show chart just generated by QLearning
		final Chart c = new Chart("QLearning-SoftMax",parameterSettings);
        c.pack();
        RefineryUtilities.centerFrameOnScreen(c);
        c.setVisible(true);
		
	}
}
