package main;

import org.jfree.ui.RefineryUtilities;

import agents.Predator;
import agents.Prey;

public class MainSoftmaxQL {

	public static void main(String[] args) {
		
		SoftmaxQLearning env = new SoftmaxQLearning(new Predator(0, 0),
				new Prey(5, 5));
		env.run();
		
		double[][] parameterSettings = {{0.3,0.5,1,15}, {0.3, 0.6, 1, 15}, {0.3, 0.7, 1, 15}};
		env.run(parameterSettings);
		// Show chart just generated by QLearning
		final Chart c = new Chart("QLearning-SoftMax",parameterSettings);
        c.pack();
        RefineryUtilities.centerFrameOnScreen(c);
        c.setVisible(true);
		
	}
}
