package main;


import org.jfree.ui.RefineryUtilities;
import agents.Predator;
import agents.PreyMiniMaxQ;

public class MainMiniMaxQ {

	public static void main(String[] args) {
		
		MiniMaxQ env = new MiniMaxQ(new Predator(0, 0),
				new PreyMiniMaxQ(5, 5));
		double[][] parameterSettings = {{0.5,0.5,0.1,1.0,1.0}};
		env.run(parameterSettings);
		// Show chart just generated by QLearning
		final Chart c = new Chart("MiniMaxQ",parameterSettings);
        c.pack();
        RefineryUtilities.centerFrameOnScreen(c);
        c.setVisible(true);
	}
}
