package main;


import org.jfree.ui.RefineryUtilities;
import agents.Predator;
import agents.Prey;

public class MainQL {

	public static void main(String[] args) {
		
		QLearning env = new QLearning(new Predator(0, 0),
				new Prey(5, 5));
		env.run();
		String[] fileNames={"output1.txt","output2.txt","output3.txt","output4.txt","output5.txt",};
		// Show chart just generated by QLearning
		final Chart c = new Chart("QLearning",fileNames);
        c.pack();
        RefineryUtilities.centerFrameOnScreen(c);
        c.setVisible(true);
	}
}
