package main;


import org.jfree.ui.RefineryUtilities;
import agents.Predator;
import agents.Prey;

public class MainMCOnP {

	public static void main(String[] args) {
		
		MonteCarloOnPolicy env = new MonteCarloOnPolicy(new Predator(0, 0),
				new Prey(5, 5));
		double[][] parameterSettings = {{0.1,0.2,0.1,15},{0.2,0.2,0.1,15},{0.3,0.2,0.1,15},{0.4,0.2,0.1,15},{0.5,0.2,0.1,15}};
		env.run(parameterSettings);
		// Show chart just generated by QLearning
		final Chart c = new Chart("Monte Carlo On-Policy",parameterSettings);
        c.pack();
        RefineryUtilities.centerFrameOnScreen(c);
        c.setVisible(true);
	}
}
